module.exports = {
  User: require('./User.model'),
  Admin: require('./Admin.model'),
  Page: require('./Page.model'),
  Characteristics: require('./Characteristics.model'),
  Question: require('./Question.model'),
  Romantiks: require('./Romantiks.model'),
  Plans: require('./Plans.model'),
  Sound: require('./Sound.model'),
  Education: require('./Education.model'),
  UserCharacteristics: require('./UserCharacteristics.model'),
  UserDatingPreferences: require('./UserDatingPreferences.model'),
  UserQusetionaryReport: require('./UserQuestionaryReport.model'),
  Tutorial: require('./Tutorial.model'),
  Post: require('./Post.model'),
  LikePost: require('./LikePost.model'),
  LikeProfile: require('./LikeProfile.model'),
  LoveProfile: require('./LoveProfile.model'),
  Notification: require('./Notification.model'),
  HoldProfile: require('./HoldProfile.model'),
  LockProfile: require('./LockProfile.model'),
  UserPlan: require('./UserPlan.model'),
  Country: require('./Country.model'),
  Reward: require('./Reward.model'),
  UserActivity: require('./UserActivity.model'),
  UserWallet: require('./UserWallet.model'),
  UserEarning: require('./UserEarning.model'),
  SuperLikeProfile: require('./SuperLikeProfile.model'),
  UserRewardActivity: require('./UserRewardActivity.model'),
  CurrencyActionsReplenish: require('./CurrencyActionsReplenish.model'),
  Chat: require('./Chat.model'),
  UserReward: require('./UserReward.model'),
  UserRecord: require('./UserRecord.model'),
  ChatColor: require('./ChatColor.model'),
  UserChatColor: require('./UserChatColor.model'),
  ZodiacImage:require('./ZodiacImage.model'),
  Game:require('./Game.model'),
  GameHint:require('./GameHint.model'),
  GameHintVideo:require('./GameHintVideo.model'),
  CurrentGame:require('./CurrentGame.model'),
  Stage:require('./Stage.model'),
  Level:require('./Level.model'),
  Pattern:require('./Pattern.model'),
  UserGame:require('./UserGame.model'),
  UserZodiacRecord:require('./UserZodiacRecord.model'),
  UserZodiacSign:require('./UserZodiacSign.model'),
  UserPaymentDetail:require('./UserPaymentDetail.model')
}
